# Generated by Django 3.1.4 on 2021-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210105_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', through='account.Contact', to='account.Profile'),
        ),
    ]
